/**
 * ChatGPT Custom GPT / Actions API.
 *
 * Auth key is hardcoded (no env) so you can paste it straight into ChatGPT
 * Actions authentication. Treat the key like a password — anyone with it can
 * call these endpoints.
 *
 * Base paths: /api/gpt/*
 * OpenAPI:    GET /api/gpt/openapi.json  (public — for Actions schema import)
 */
import type http from "node:http";
import { randomBytes } from "node:crypto";
import { prisma } from "@sportybet/db";
import {
  getExpertPicks,
  getExpertRecord,
  getExpertRoi,
  getValuePicks,
  getCombos,
  buildAnalystSlip,
  type GameType,
} from "./analyst.js";
import { getPredictions } from "./predictions.js";
import {
  placeDemoBet,
  placeDemoBetFromSelections,
  autoGenerateDemoSlips,
  getDemoWallet,
  getDemoDailyStats,
  getDemoLeaderboard,
  deleteDemoBet,
} from "./demo.js";
import { createBookingCode } from "./booker.js";
import { planForTips, legsForFixtureKeys } from "./forebet-ai.js";
import {
  lastRunAt,
  nextRunAt,
  lastSummary,
  intervalSec,
} from "./scheduler.js";
import {
  readDashboardSnapshot,
  snapshotIsFresh,
  isServerlessRuntime,
} from "./snapshot.js";
import { cached } from "./cache.js";
import { telegramClientEnabled } from "./adapters/telegram-client.js";

/** Paste this into ChatGPT Actions → Authentication → API Key. */
export const CHATGPT_API_KEY =
  "svpai_gpt_sk_9f2e7c4a1b8d6e0f3c5a7b9d1e4f6a8c";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers":
    "Authorization, Content-Type, X-Api-Key, X-Wallet-Id",
  "Access-Control-Expose-Headers": "X-Wallet-Id",
};

function json(
  res: http.ServerResponse,
  status: number,
  body: unknown,
  extraHeaders?: Record<string, string>,
): void {
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    ...CORS,
    ...(extraHeaders ?? {}),
  });
  res.end(JSON.stringify(body));
}

function readBody(req: http.IncomingMessage, maxBytes = 256 * 1024): Promise<string> {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks: Buffer[] = [];
    req.on("data", (c: Buffer) => {
      size += c.length;
      if (size > maxBytes) {
        reject(new Error("payload too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

function extractApiKey(req: http.IncomingMessage): string | null {
  const auth = req.headers.authorization;
  if (typeof auth === "string") {
    const m = /^Bearer\s+(.+)$/i.exec(auth.trim());
    if (m) return m[1].trim();
  }
  const hdr = req.headers["x-api-key"];
  if (typeof hdr === "string" && hdr.trim()) return hdr.trim();
  return null;
}

function authorized(req: http.IncomingMessage): boolean {
  const key = extractApiKey(req);
  return !!key && key === CHATGPT_API_KEY;
}

function walletFrom(
  req: http.IncomingMessage,
  body?: { walletId?: string },
  query?: URLSearchParams,
): { owner: string; walletId: string; created: boolean } {
  const fromHdr =
    typeof req.headers["x-wallet-id"] === "string"
      ? req.headers["x-wallet-id"].trim()
      : "";
  const fromBody = String(body?.walletId ?? "").trim();
  const fromQ = query?.get("walletId")?.trim() ?? "";
  let id = fromHdr || fromBody || fromQ;
  let created = false;
  if (!id || !/^[a-f0-9]{16,64}$/i.test(id)) {
    id = randomBytes(16).toString("hex");
    created = true;
  }
  return { owner: `gpt:${id.toLowerCase()}`, walletId: id.toLowerCase(), created };
}

function validGameType(v: unknown): GameType {
  const s = String(v ?? "result");
  const ok = ["result", "goals", "btts", "safe", "both"] as const;
  return (ok as readonly string[]).includes(s) ? (s as GameType) : "result";
}

function openApiDoc(baseUrl: string) {
  const bearer = {
    type: "http" as const,
    scheme: "bearer",
    bearerFormat: "API Key",
    description: `Use the Sporty GPT API key as the Bearer token.`,
  };
  return {
    openapi: "3.1.0",
    info: {
      title: "Sport Value Pick — ChatGPT Actions API",
      version: "1.0.0",
      description:
        "Read booking codes, expert/value/combo picks, predictions, track record, and run VIRTUAL demo simulations (no real money). Authenticate every call except this OpenAPI document with the API key as Bearer token. Always pass walletId from a previous response when continuing a simulation session.",
    },
    servers: [{ url: baseUrl.replace(/\/$/, "") }],
    components: {
      securitySchemes: { bearerAuth: bearer },
      schemas: {
        Error: {
          type: "object",
          properties: {
            ok: { type: "boolean" },
            error: { type: "string" },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
    paths: {
      "/api/gpt/health": {
        get: {
          operationId: "gptHealth",
          summary: "API + crawl health",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/status": {
        get: {
          operationId: "gptStatus",
          summary: "Crawl status, KPIs, snapshot freshness",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/codes": {
        get: {
          operationId: "gptCodes",
          summary: "Newest human booking codes (non-INVALID)",
          parameters: [
            {
              name: "limit",
              in: "query",
              schema: { type: "integer", default: 40, maximum: 100 },
            },
            {
              name: "day",
              in: "query",
              description: "YYYY-MM-DD Africa/Lagos filter",
              schema: { type: "string" },
            },
          ],
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/predictions": {
        get: {
          operationId: "gptPredictions",
          summary: "External model predictions feed",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/expert": {
        get: {
          operationId: "gptExpertPicks",
          summary: "Expert picks simulation pool",
          parameters: [
            { name: "count", in: "query", schema: { type: "integer", default: 10, maximum: 40 } },
            { name: "days", in: "query", schema: { type: "integer", default: 5, maximum: 14 } },
            {
              name: "gameType",
              in: "query",
              schema: {
                type: "string",
                enum: ["result", "goals", "btts", "safe", "both"],
                default: "result",
              },
            },
            {
              name: "minConfidence",
              in: "query",
              description: "0–1 fraction",
              schema: { type: "number", default: 0.55 },
            },
          ],
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/value": {
        get: {
          operationId: "gptValuePicks",
          summary: "Value picks (bigger odds)",
          parameters: [
            { name: "count", in: "query", schema: { type: "integer", default: 15, maximum: 30 } },
            { name: "days", in: "query", schema: { type: "integer", default: 7, maximum: 14 } },
            { name: "minOdds", in: "query", schema: { type: "number", default: 1.8 } },
          ],
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/combos": {
        get: {
          operationId: "gptCombos",
          summary: "Ready-made combo slips",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/expert/record": {
        get: {
          operationId: "gptExpertRecord",
          summary: "Settled expert pick hit-rate",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/expert/roi": {
        get: {
          operationId: "gptExpertRoi",
          summary: "Expert picks ROI summary",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/wallet": {
        get: {
          operationId: "gptWallet",
          summary: "Demo simulation wallet (virtual ₦)",
          parameters: [
            {
              name: "walletId",
              in: "query",
              description: "Reuse from a prior response",
              schema: { type: "string" },
            },
          ],
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/leaderboard": {
        get: {
          operationId: "gptLeaderboard",
          summary: "Demo simulation leaderboard",
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/simulate/bet": {
        post: {
          operationId: "gptSimulateBet",
          summary: "Place a VIRTUAL accumulator on fixture keys",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["keys", "stake"],
                  properties: {
                    keys: {
                      type: "array",
                      items: { type: "string" },
                      description: "Fixture keys from expert/value/predictions (home|away style)",
                    },
                    stake: { type: "number", description: "Virtual ₦ stake" },
                    gameType: {
                      type: "string",
                      enum: ["result", "goals", "btts", "safe", "both"],
                    },
                    origin: { type: "string" },
                    walletId: { type: "string" },
                  },
                },
              },
            },
          },
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/simulate/code": {
        post: {
          operationId: "gptSimulateCode",
          summary: "Virtually stake an existing booking code's selections",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["code", "stake"],
                  properties: {
                    code: { type: "string" },
                    stake: { type: "number" },
                    walletId: { type: "string" },
                  },
                },
              },
            },
          },
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/simulate/analyst": {
        post: {
          operationId: "gptSimulateAnalyst",
          summary: "Build a tailored AI analyst slip (preview only)",
          requestBody: {
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    numGames: { type: "integer" },
                    minOdds: { type: "number" },
                    maxOdds: { type: "number" },
                  },
                },
              },
            },
          },
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/simulate/auto": {
        post: {
          operationId: "gptSimulateAuto",
          summary: "Auto-generate several virtual demo slips into the wallet",
          requestBody: {
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: { walletId: { type: "string" } },
                },
              },
            },
          },
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/simulate/delete": {
        post: {
          operationId: "gptSimulateDelete",
          summary: "Delete one demo bet from the wallet",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["id"],
                  properties: {
                    id: { type: "string" },
                    walletId: { type: "string" },
                  },
                },
              },
            },
          },
          responses: { "200": { description: "OK" } },
        },
      },
      "/api/gpt/book": {
        post: {
          operationId: "gptBookCode",
          summary: "Create a real SportyBet share/booking code from fixture keys",
          requestBody: {
            required: true,
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["keys"],
                  properties: {
                    keys: { type: "array", items: { type: "string" } },
                    gameType: {
                      type: "string",
                      enum: ["result", "goals", "btts", "safe", "both"],
                    },
                  },
                },
              },
            },
          },
          responses: { "200": { description: "OK" } },
        },
      },
    },
  };
}

/**
 * Handle /api/gpt/* routes. Returns true if the request was fully handled.
 * Call this before the APP_PASSWORD gate.
 */
export async function handleChatGptApi(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  url: URL,
): Promise<boolean> {
  if (!url.pathname.startsWith("/api/gpt")) return false;

  if (req.method === "OPTIONS") {
    res.writeHead(204, CORS);
    res.end();
    return true;
  }

  // Public schema for ChatGPT Actions import
  if (url.pathname === "/api/gpt/openapi.json" && req.method === "GET") {
    const proto = (req.headers["x-forwarded-proto"] as string) || "https";
    const host = (req.headers["x-forwarded-host"] as string) || req.headers.host || "localhost";
    const base = `${proto}://${host}`;
    json(res, 200, openApiDoc(base));
    return true;
  }

  if (!authorized(req)) {
    json(res, 401, {
      ok: false,
      error: "Unauthorized. Send Authorization: Bearer <API_KEY> or X-Api-Key.",
    });
    return true;
  }

  try {
    if (url.pathname === "/api/gpt/health" && req.method === "GET") {
      json(res, 200, {
        ok: true,
        service: "sport-value-pick-gpt",
        lastRunAt: lastRunAt ? new Date(lastRunAt).toISOString() : null,
        nextRunAt: nextRunAt ? new Date(nextRunAt).toISOString() : null,
        lastSummary,
        intervalSec,
        telegramApi: telegramClientEnabled() ? "live" : "web-preview",
        serverless: isServerlessRuntime(),
      });
      return true;
    }

    if (url.pathname === "/api/gpt/status" && req.method === "GET") {
      const snap = await readDashboardSnapshot();
      const [activeCount, totalCodes, sourceCount] = await Promise.all([
        prisma.humanCode.count({ where: { status: "ACTIVE" } }),
        prisma.humanCode.count({ where: { status: { not: "INVALID" } } }),
        prisma.source.count({ where: { enabled: true } }),
      ]);
      json(res, 200, {
        ok: true,
        lastRunAt: lastRunAt
          ? new Date(lastRunAt).toISOString()
          : snap?.payload.lastRunAt ?? null,
        lastSummary: lastSummary || snap?.payload.lastSummary || "",
        activeCount: snap && snapshotIsFresh(snap.updatedAt) ? snap.payload.activeCount : activeCount,
        totalCodes: snap && snapshotIsFresh(snap.updatedAt) ? snap.payload.totalCodes : totalCodes,
        sourceCount: snap && snapshotIsFresh(snap.updatedAt) ? snap.payload.sourceCount : sourceCount,
        snapshot: snap
          ? {
              updatedAt: snap.updatedAt.toISOString(),
              fresh: snapshotIsFresh(snap.updatedAt),
            }
          : null,
      });
      return true;
    }

    if (url.pathname === "/api/gpt/codes" && req.method === "GET") {
      const limit = Math.min(100, Math.max(1, Number(url.searchParams.get("limit")) || 40));
      const day = url.searchParams.get("day")?.trim() || "";
      const snap = isServerlessRuntime() ? await readDashboardSnapshot() : null;
      if (snap && snapshotIsFresh(snap.updatedAt)) {
        let rows = snap.payload.codes as Array<Record<string, unknown>>;
        if (day) {
          const gte = new Date(`${day}T00:00:00+01:00`).getTime();
          const lte = new Date(`${day}T23:59:59.999+01:00`).getTime();
          rows = rows.filter((c) => {
            const t = new Date(String(c.foundAt)).getTime();
            return t >= gte && t <= lte;
          });
        }
        json(res, 200, {
          ok: true,
          fromSnapshot: true,
          totalCodes: snap.payload.totalCodes,
          codes: rows.slice(0, limit).map(summarizeCode),
        });
        return true;
      }
      const where: Record<string, unknown> = { status: { not: "INVALID" } };
      if (day) {
        where.foundAt = {
          gte: new Date(`${day}T00:00:00+01:00`),
          lte: new Date(`${day}T23:59:59.999+01:00`),
        };
      }
      const [codes, totalCodes] = await Promise.all([
        prisma.humanCode.findMany({
          where,
          orderBy: { foundAt: "desc" },
          take: limit,
          include: { source: true, score: true },
        }),
        prisma.humanCode.count({ where: { status: { not: "INVALID" } } }),
      ]);
      json(res, 200, {
        ok: true,
        fromSnapshot: false,
        totalCodes,
        codes: codes.map(summarizeCode),
      });
      return true;
    }

    if (url.pathname === "/api/gpt/predictions" && req.method === "GET") {
      const data = await getPredictions();
      json(res, 200, { ok: true, count: data.length, predictions: data.slice(0, 80) });
      return true;
    }

    if (url.pathname === "/api/gpt/expert" && req.method === "GET") {
      const count = Math.min(40, Math.max(1, Number(url.searchParams.get("count")) || 10));
      const days = Math.min(14, Math.max(1, Number(url.searchParams.get("days")) || 5));
      const gameType = validGameType(url.searchParams.get("gameType"));
      const minConfidence = Math.min(
        0.95,
        Math.max(0, Number(url.searchParams.get("minConfidence")) || 0.55),
      );
      const seed = Math.floor(Date.now() / (8 * 60_000));
      const result = await cached(
        `gpt:expert:${count}:${days}:${gameType}:${minConfidence}:${seed}`,
        480,
        () => getExpertPicks({ count, days, gameType, minConfidence, seed }),
      );
      json(res, 200, { ok: true, ...result });
      return true;
    }

    if (url.pathname === "/api/gpt/value" && req.method === "GET") {
      const count = Math.min(30, Math.max(1, Number(url.searchParams.get("count")) || 15));
      const days = Math.min(14, Math.max(1, Number(url.searchParams.get("days")) || 7));
      const minOdds = Math.max(1.01, Number(url.searchParams.get("minOdds")) || 1.8);
      const seed = Math.floor(Date.now() / (8 * 60_000));
      const result = await cached(
        `gpt:value:${count}:${days}:${minOdds}:${seed}`,
        480,
        () => getValuePicks({ count, days, minOdds, seed }),
      );
      json(res, 200, { ok: true, ...result });
      return true;
    }

    if (url.pathname === "/api/gpt/combos" && req.method === "GET") {
      const seed = Math.floor(Date.now() / (10 * 60_000));
      const combos = await cached(`gpt:combos:${seed}`, 600, () => getCombos(seed));
      json(res, 200, { ok: true, combos });
      return true;
    }

    if (url.pathname === "/api/gpt/expert/record" && req.method === "GET") {
      const data = await getExpertRecord();
      json(res, 200, { ok: true, record: data });
      return true;
    }

    if (url.pathname === "/api/gpt/expert/roi" && req.method === "GET") {
      const data = await getExpertRoi();
      json(res, 200, { ok: true, roi: data });
      return true;
    }

    if (url.pathname === "/api/gpt/wallet" && req.method === "GET") {
      const w = walletFrom(req, undefined, url.searchParams);
      const [wallet, daily] = await Promise.all([
        getDemoWallet(w.owner),
        getDemoDailyStats(w.owner),
      ]);
      json(
        res,
        200,
        { ok: true, walletId: w.walletId, wallet, daily },
        { "X-Wallet-Id": w.walletId },
      );
      return true;
    }

    if (url.pathname === "/api/gpt/leaderboard" && req.method === "GET") {
      const board = await getDemoLeaderboard(null).catch(() => []);
      json(res, 200, { ok: true, leaderboard: board });
      return true;
    }

    if (url.pathname === "/api/gpt/simulate/bet" && req.method === "POST") {
      const body = JSON.parse((await readBody(req)) || "{}") as {
        keys?: string[];
        stake?: number;
        gameType?: string;
        origin?: string;
        walletId?: string;
      };
      const keys = Array.isArray(body.keys) ? body.keys.map(String) : [];
      const stake = Number(body.stake) || 0;
      const gameType = validGameType(body.gameType);
      const w = walletFrom(req, body);
      const result = await placeDemoBet(
        w.owner,
        keys,
        stake,
        gameType,
        String(body.origin ?? "chatgpt").slice(0, 20),
      ).catch((e) => ({
        ok: false as const,
        error: `Demo bet failed: ${e instanceof Error ? e.message : e}`,
      }));
      json(res, result.ok ? 200 : 400, { ...result, walletId: w.walletId }, {
        "X-Wallet-Id": w.walletId,
      });
      return true;
    }

    if (url.pathname === "/api/gpt/simulate/code" && req.method === "POST") {
      const body = JSON.parse((await readBody(req)) || "{}") as {
        code?: string;
        stake?: number;
        walletId?: string;
      };
      const code = String(body.code ?? "")
        .trim()
        .toUpperCase()
        .slice(0, 24);
      const stake = Number(body.stake) || 0;
      const w = walletFrom(req, body);
      const hcRows = code
        ? await prisma.humanCode
            .findMany({ where: { code }, orderBy: { foundAt: "desc" }, take: 10 })
            .catch(() => [])
        : [];
      const hc =
        hcRows.find(
          (r) => Array.isArray(r.selections) && (r.selections as unknown[]).length > 0,
        ) ??
        hcRows[0] ??
        null;
      let sels: unknown[] = Array.isArray(hc?.selections) ? (hc!.selections as unknown[]) : [];
      let foundAny = !!hc;
      if (!sels.length) {
        const gc = code
          ? await prisma.generatedCode.findFirst({
              where: { code },
              orderBy: { createdAt: "desc" },
            })
          : null;
        if (gc) {
          foundAny = true;
          if (Array.isArray(gc.legs)) sels = gc.legs as unknown[];
        }
      }
      const result = !foundAny
        ? { ok: false as const, error: "That code isn't on the dashboard." }
        : !sels.length
          ? {
              ok: false as const,
              error: "This code's game details haven't been verified yet.",
            }
          : await placeDemoBetFromSelections(
              w.owner,
              sels as Record<string, unknown>[],
              stake,
              "code",
            ).catch((e) => ({
              ok: false as const,
              error: `Demo bet failed: ${e instanceof Error ? e.message : e}`,
            }));
      json(res, result.ok ? 200 : 400, { ...result, walletId: w.walletId }, {
        "X-Wallet-Id": w.walletId,
      });
      return true;
    }

    if (url.pathname === "/api/gpt/simulate/analyst" && req.method === "POST") {
      const body = JSON.parse((await readBody(req)) || "{}") as {
        numGames?: number;
        minOdds?: number;
        maxOdds?: number;
      };
      const slip = await buildAnalystSlip({
        numGames: body.numGames,
        minOdds: body.minOdds,
        maxOdds: body.maxOdds,
      }).catch(() => ({
        legs: [],
        totalOdds: 1,
        combinedChance: null,
        requested: body,
        note: "Something went wrong building the slip — try again.",
      }));
      json(res, 200, { ok: slip.legs.length > 0, slip });
      return true;
    }

    if (url.pathname === "/api/gpt/simulate/auto" && req.method === "POST") {
      const body = JSON.parse((await readBody(req)) || "{}") as { walletId?: string };
      const w = walletFrom(req, body);
      const entries = await autoGenerateDemoSlips(w.owner).catch(() => []);
      json(res, 200, { ok: true, walletId: w.walletId, entries }, {
        "X-Wallet-Id": w.walletId,
      });
      return true;
    }

    if (url.pathname === "/api/gpt/simulate/delete" && req.method === "POST") {
      const body = JSON.parse((await readBody(req)) || "{}") as {
        id?: string;
        walletId?: string;
      };
      const w = walletFrom(req, body);
      const betId = String(body.id ?? "").slice(0, 40);
      if (!betId) {
        json(res, 400, { ok: false, error: "Missing bet id.", walletId: w.walletId });
        return true;
      }
      const out = await deleteDemoBet(w.owner, betId).catch((e) => ({
        ok: false as const,
        error: `Delete failed: ${e instanceof Error ? e.message : e}`,
      }));
      json(res, 200, { ...out, walletId: w.walletId }, { "X-Wallet-Id": w.walletId });
      return true;
    }

    if (url.pathname === "/api/gpt/book" && req.method === "POST") {
      const body = JSON.parse((await readBody(req)) || "{}") as {
        keys?: string[];
        gameType?: string;
      };
      const keys = Array.isArray(body.keys) ? body.keys.map(String) : [];
      const gameType = validGameType(body.gameType);
      if (!keys.length) {
        json(res, 400, { ok: false, error: "Provide keys[] from expert/value picks." });
        return true;
      }
      if (keys.length > 70) {
        json(res, 400, { ok: false, error: "Maximum 70 matches per booking code." });
        return true;
      }
      const preds = await getPredictions();
      const wanted = preds.filter(
        (p) => p.home && p.away && keys.includes(`${p.home}|${p.away}`.toLowerCase()),
      );
      const { legs: tipLegs, matchedKeys: tipMatched } = wanted.length
        ? await planForTips(wanted)
        : { legs: [], matchedKeys: [] as string[] };
      const remainingKeys = keys.filter((k) => !tipMatched.includes(k));
      const { legs: directLegs } = await legsForFixtureKeys(remainingKeys, gameType);
      const legs = [...tipLegs, ...directLegs];
      if (!legs.length) {
        json(res, 400, {
          ok: false,
          error: "Could not resolve bookable legs for those keys.",
        });
        return true;
      }
      const booked = await createBookingCode(legs);
      if (booked.error || !booked.code) {
        json(res, 400, { ok: false, error: booked.error || "Booking failed" });
        return true;
      }
      json(res, 200, { ok: true, ...booked });
      return true;
    }

    json(res, 404, {
      ok: false,
      error: "Unknown GPT API route. See GET /api/gpt/openapi.json",
    });
    return true;
  } catch (err) {
    json(res, 500, {
      ok: false,
      error: err instanceof Error ? err.message : String(err),
    });
    return true;
  }
}

function summarizeCode(c: Record<string, unknown> | {
  code: string;
  status: string;
  foundAt: Date | string;
  totalOdds?: unknown;
  selections?: unknown;
  source?: { name?: string; type?: string } | null;
  score?: { overall?: number } | null;
}) {
  const src = (c as { source?: { name?: string; type?: string } }).source;
  const score = (c as { score?: { overall?: number } }).score;
  const sels = (c as { selections?: unknown }).selections;
  return {
    code: (c as { code: string }).code,
    status: (c as { status: string }).status,
    foundAt: (c as { foundAt: Date | string }).foundAt,
    totalOdds: (c as { totalOdds?: unknown }).totalOdds ?? null,
    selectionCount: Array.isArray(sels) ? sels.length : 0,
    source: src ? { name: src.name, type: src.type } : null,
    score: score?.overall ?? null,
  };
}
